name: Build and push the latest build to staging  # Nombre del flujo de trabajo

on:  # Definición de los eventos que desencadenarán el flujo de trabajo
  push:  # El flujo de trabajo se ejecutará en eventos push
    branches: [ main ]  # Solo se ejecutará cuando se haga push a la rama principal

jobs:  # Definición de los trabajos que se ejecutarán en este flujo de trabajo
  build_push_image:  # Nombre del trabajo
    runs-on: ubuntu-20.04  # El trabajo se ejecutará en un runner de GitHub que usa Ubuntu 20.04

    steps:  # Lista de pasos que se ejecutarán como parte del trabajo
      - name: Checkout repository  # Paso para clonar el repositorio en el runner
        uses: actions/checkout@v2

      - name: Set up Buildx  # Paso para configurar Buildx, una extensión de Docker para construir imágenes
        uses: docker/setup-buildx-action@v3.0.0

      - name: Docker Login  # Paso para iniciar sesión en el registro de Docker
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ secrets.ACR_NAME }}  # Dirección del registro de Docker almacenada en secretos
          username: ${{ secrets.ACR_LOGIN }}  # Nombre de usuario almacenado en secretos
          password: ${{ secrets.ACR_PASSWORD }}  # Contraseña o token de acceso personal almacenado en secretos

      - name: Build and push staging images  # Paso para construir y enviar las imágenes de Docker a staging
        uses: docker/build-push-action@v5.0.0
        with:
          context: .  # Contexto de la construcción, la raíz del repositorio
          push: true  # Indica que la imagen debe ser enviada al registro
          tags: ${{ secrets.ACR_NAME }}/contoso-website:latest  # Etiqueta de la imagen que se construirá y enviará
